version: '2'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    environment: 
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESS_DB: ${DATABASE_DB}
    volumes:
      - ./pgdata:/var/lib/postgres/data 
volumes:
  pgdata: